# Generated by Django 5.2.17 on 2026-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='secteur',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('finance', 'Finance'), ('sante', 'Santé'), ('industrie', 'Industrie'), ('commerce', 'Commerce'), ('education', 'Éducation'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='entreprise',
            constraint=models.UniqueConstraint(fields=('nom', 'ville'), name='unique_nom_ville'),
        ),
    ]
