# Generated by Django 5.2.17 on 2026-10-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_alter_entreprise_secteur_entreprise_unique_nom_ville'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EnseignantReferent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('promotion', models.CharField(max_length=50)),
                ('competences', models.ManyToManyField(blank=True, related_name='etudiants', to='stages.competence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('nb_places', models.IntegerField()),
                ('competences', models.ManyToManyField(blank=True, related_name='offres', to='stages.competence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='stages.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='TuteurEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin'), ('A', 'Autre')], default='M', max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='stages.entreprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('enseignant_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='stages.enseignantreferent')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.entreprise')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.etudiant')),
                ('tuteur_entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='stages.tuteurentreprise')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depot', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.etudiant')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.offre')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='stages.stage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('etudiant', 'offre'), name='candidature_unique')],
            },
        ),
    ]
