# Generated by Django 5.2.17 on 2026-10-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_competence_enseignantreferent_etudiant_offre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='stages.entreprise'),
        ),
    ]
