# Generated by Django 5.2.17 on 2026-10-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_alter_offre_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.etudiant'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.offre'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='stages.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.entreprise'),
        ),
        migrations.AlterField(
            model_name='tuteurentreprise',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuteurs', to='stages.entreprise'),
        ),
    ]
