# Generated by Django 5.2.17 on 2026-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_alter_candidature_etudiant_alter_candidature_offre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
